image: "change_me_i_am_image"

env:
  MYSQL_DB_HOST: "change_me_i_am_db_host"
  MYSQL_DATABASE_NAME: "change_me_i_am_db_name"
  MYSQL_USERNAME: "change_me_i_am_username"
  MYSQL_PASSWORD: "change_me_i_am_password"

countOfReplicas: 2