apiVersion: apps/v1
kind: Deployment
metadata:
  name: itunes-data-loader-deployment
spec:
  replicas: {{ .Values.countOfReplicas }}
  selector:
    matchLabels:
      app: itunes-data-loader
  template:
    metadata:
      labels:
        app: itunes-data-loader
    spec:
      containers:
        - name: itunes-data-loader
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_DB_HOST
              value: {{ .Values.env.MYSQL_DB_HOST }}
            - name: MYSQL_DATABASE_NAME
              value: {{ .Values.env.MYSQL_DATABASE_NAME }}
            - name: MYSQL_USERNAME
              value: {{ .Values.env.MYSQL_USERNAME }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.env.MYSQL_PASSWORD }}
