apiVersion: v1
kind: Service
metadata:
  name: itunes-data-loader
  labels:
    env: prod
    owner: krasavin
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: itunes-data-loader